name: Release Issues Summary

on:
  create:
    branches:
      - 'release-*'

jobs:
  compile_issues:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
      with:
        fetch-depth: 0

    - name: Extract commits and issues
      run: |
        echo "Commits from main to ${GITHUB_REF#refs/heads/}:"
        git log main..${GITHUB_REF#refs/heads/} --pretty=format:"%H %s"


    - name: Create issue on GitHub with the list of included issues
      uses: JasonEtco/create-an-issue@v2
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        filename: .github/release-report.md
        title: "Issues included in release ${GITHUB_REF#refs/heads/}"
        body: |
          This release includes the following issues:
          $(cat issues.txt)
