name: Release Issues Summary

on:
  create:
    branches:
      - 'release-*'

jobs:
  compile_issues:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
      with:
        fetch-depth: 0

    - name: List all branches
      run: git branch -a

    - name: Ensure main and release branch are fetched
      run: |
        git fetch --all
        git checkout main
        git checkout ${GITHUB_REF#refs/heads/}
        git branch -a

    - name: Extract commits and issues
      run: |
        echo "Commits from main to ${GITHUB_REF#refs/heads/}:"
        git log main..${GITHUB_REF#refs/heads/} --pretty=format:"%H %s"
